--- #Delimits each Cloud Environment
datacenterRegistries:
  - !datacenter
    name: datacenter1
    amount: 1
    allocationPolicyAlias: Simple
    architecture: x86
    os: Linux
    vmm: Xen
    upperUtilizationThreshold: 0.8
    lowerUtilizationThreshold: 0.2
    vmMigration: enabled
    schedulingInterval: 30
    monitoringInterval: 180
    costPerSec: 0.1
    costPerMem: 0.05
    costPerStorage: 0.001
    costPerBw: 0.1
    sanList:
      ##se o nome não for informado em qualquer elemento, ele deve ser criado automaticamente
      - !san
        name: san1
        capacity: 10000
        bandwidth: 10000
        networkLatency: 5
      - !san
        name:
        capacity: 50000
        bandwidth: 20000
        networkLatency: 5
    hostList:
      ##se o id não for informado em qualquer elemento, ele deve ser criado automaticamente
      - !host
        id: 1
        amount: 10
        ram: 80000
        bw: 50000
        storage: 500000
        maxPower: 250
        staticPowerPercent: 0.7
        numOfPes: 4
        mipsPerPe: 100000
        schedulingPolicyAlias: TimeShared
        powerModelAlias: Linear
        ramProvisionerAlias: Simple
        bwProvisionerAlias: Simple
        peProvisionerAlias: Simple
      - !host
        #id: #se omitido, será automaticamente gerado
        amount: 4
        ram: 1000000
        bw: 80000
        storage: 40000
        maxPower: 250
        staticPowerPercent: 0.7
        numOfPes: 4
        mipsPerPe: 50000
        schedulingPolicyAlias: TimeShared
        powerModelAlias: Linear
        ramProvisionerAlias: Simple
        bwProvisionerAlias: Simple
        peProvisionerAlias: Simple
  #se o nome não for informado em qualquer elemento, ele deve ser criado automaticamente
  - !datacenter
    name: 
    amount: 2
    allocationPolicyAlias: Simple
    architecture: x86
    os: Linux
    vmm: Xen
    upperUtilizationThreshold: 0.8
    lowerUtilizationThreshold: 0.2
    vmMigration: enabled
    schedulingInterval: 30
    monitoringInterval: 180
    costPerSec: 0.1
    costPerMem: 0.05
    costPerStorage: 0.001
    costPerBw: 0.1
    sanList:
      ##se o nome não for informado em qualquer elemento, ele deve ser criado automaticamente
      - !san
        name: san1
        capacity: 10000
        bandwidth: 10000
        networkLatency: 5
      - !san
        name:
        capacity: 50000
        bandwidth: 20000
        networkLatency: 5
    hostList:
      ##se o nome não for informado em qualquer elemento, ele deve ser criado automaticamente
      - !host
        id: 1
        amount: 10
        ram: 500000
        bw: 40000
        storage: 1000000
        maxPower: 250
        staticPowerPercent: 0.7
        numOfPes: 4
        mipsPerPe: 200000
        schedulingPolicyAlias: TimeShared
        powerModelAlias: Linear
        ramProvisionerAlias: Simple
        bwProvisionerAlias: Simple
        peProvisionerAlias: Simple
      - !host
        #id: #se omitido, será automaticamente gerado
        amount: 4
        ram: 2000000
        bw: 120000
        storage: 850000
        maxPower: 250
        staticPowerPercent: 0.7
        numOfPes: 4
        mipsPerPe: 400000
        schedulingPolicyAlias: TimeShared
        powerModelAlias: Linear
        ramProvisionerAlias: Simple
        bwProvisionerAlias: Simple
        peProvisionerAlias: Simple
customerRegistries:
  - !customer
    name: Customer1
    amount: 1
    vmList:
      - !vm
        #id: #se omitido, será automaticamente gerado
        amount: 10
        size: 500
        pesNumber: 2
        mips: 1000
        ram: 2000
        bw: 100
        priority: 1
        vmm: Xen
        schedulingPolicyAlias: TimeShared
      - !vm
        amount: 8
        size: 400
        pesNumber: 4
        mips: 1000
        ram: 1400
        bw: 80
        priority: 1
        vmm: Xen
        schedulingPolicyAlias: TimeShared
    utilizationProfile:
      - !profile
        #id: #se omitido, será automaticamente gerado       
        numOfCloudlets: 5
        brokerPolicyAlias: RoundRobin
        cloudletsPesNumber: 2
        length: 100
        fileSize: 50
        outputSize: 50
        utilizationModelCpuAlias: Full
        utilizationModelRamAlias: Full
        utilizationModelBwAlias: Full
      - !profile
        numOfCloudlets: 15
        brokerPolicyAlias: RoundRobin
        cloudletsPesNumber: 1
        length: 150
        fileSize: 50
        outputSize: 50
        utilizationModelCpuAlias: Full
        utilizationModelRamAlias: Full
        utilizationModelBwAlias: Full
  - !customer
    name:
    amount: 2
    vmList:
      - !vm
        #id: #se omitido, será automaticamente gerado
        amount: 10
        size: 1000
        pesNumber: 2
        mips: 1000
        ram: 1000
        bw: 250
        priority: 1
        vmm: Xen
        schedulingPolicyAlias: TimeShared
      - !vm
        amount: 8
        size: 1000
        pesNumber: 4
        mips: 1000
        ram: 2000
        bw: 180
        priority: 1
        vmm: Xen
        schedulingPolicyAlias: TimeShared
    utilizationProfile:
      - !profile
        #id: #se omitido, será automaticamente gerado       
        numOfCloudlets: 5
        brokerPolicyAlias: RoundRobin
        cloudletsPesNumber: 2
        length: 1000
        fileSize: 80
        outputSize: 80
        utilizationModelCpuAlias: Full
        utilizationModelRamAlias: Full
        utilizationModelBwAlias: Full
      - !profile
        #numOfCloudlets: 1 #se omitido, será 1
        brokerPolicyAlias: RoundRobin
        cloudletsPesNumber: 1
        length: 1000
        fileSize: 30
        outputSize: 30
        utilizationModelCpuAlias: Full
        utilizationModelRamAlias: Full
        utilizationModelBwAlias: Full
         
      